version: '3.8'

services:
  frontend: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      - VITE_PORT=${VITE_PORT}
      - VITE_BACKEND_API_BASEURL=${VITE_BACKEND_API_BASEURL}
      - VITE_BACKEND_API_DNA_ROUTE=${VITE_BACKEND_API_DNA_ROUTE}
          